### ISSUE TITLE
Restric public access to view only?

### ISSUE THREAD

**Issue by hainesm6** [JBEI/ice#104]
When sharing entires with the public, is there anyway to restrict access to view only, preventing unwanted changes to entries?

**Comment by hplahar** [comment]
That is the default. You cannot give write public access. Are you seeing
otherwise?

**Comment by hainesm6** [comment]
Thanks for your quick response @hplahar. After a bit of fidling around it seems you're right. You can't change public entires by default. However, you can click the `editEntry()` button making it seem like you can. Then when you try to submit it, you get an `Access to requested resource denied` response. Anyway sorry for the confusion.

**Comment by hplahar** [comment]
Thanks for pointing that out. "Edit" should not be enabled if you don't have edit privileges. I will add that to the next round of bug fixes.
