### ISSUE TITLE
JBEI Registry access

### ISSUE THREAD

**Issue by Nehabansal88** [JBEI/ice#126]
Hi,
My name is Neha Bansal, a new postdoc (071907) at BSE, JBEI, LBNL. I am not able to fully access the JBEI registry! 

I can access the link https://public-registry.jbei.org/profile/4997 

But not https://registry.jbei.org/login 

Thus, there are only some 6000 strain entries that I am able to access!
Can you please help me resolve this issue? It will be helpful to me

Regards,
Neha Bansal

**Comment by chimaerase** [comment]
Hi Neha, sorry for the inconvenience.  @hplahar, is there a required LDAP group membership (JBEI?) that's missing here?  I assume that's something Neha's PI would need to take care of.

**Comment by njhillson** [comment]
This has been taken care of. Please close ticket Sent from my iPhoneOn Feb 20, 2023, at 08:54, Mark Forrer ***@***.***> wrote:﻿
Hi Neha, sorry for the inconvenience.  @hplahar, is there a required LDAP group membership (JBEI?) that's missing here?  I assume that's something Neha's PI would need to take care of.
