### ISSUE TITLE
Cannot upload sequencing data to a plasmid which isn't mine

### ISSUE THREAD

**Issue by ceiben** [JBEI/ice#23]
Was having trouble PCRing a portion of a plasmid (Keasling-1612), so I sent it in for sequencing. Got good sequencing data back showing a 4bp deletion as compared to the reference sequence (does not affect my PCR though). I would like to attach the sequencing file to inform others, but cannot (or at least I cannot figure out how). The system may be acting as designed, or maybe it's a permissions issue, but I would say that in the case of sequencing data, being able to upload sequencing files on other peoples plasmids is desirable.

**Comment by hplahar** [comment]
It is indeed acting as designed since you need edit permissions before being able to upload sequencing files. This requires a bit of thought as to how best to implement it. In the meantime I have given you write access to that plasmid

**Comment by hplahar** [comment]
This feature have been enabled
