### ISSUE TITLE
ioErrorHandler: Error #2032 when trying to save plasmid to registry from vector editor

### ISSUE THREAD

**Issue by ceiben** [JBEI/ice#24]
Was trying to upload a plasmid map file (supposedly in .gb formant) to the registry (https://registry.jbei.org/entry/47972), but received a parsing error. So then I uploaded the file to vector editor and then tried to save it to the registry from there and got the ioErrorHandler: Error #2032. Github wont It wont let me upload the pNC011.gb file, so I copied and pasted the file below. 

LOCUS       pNC011.xdna_(mod        3851 bp ds DNA     circular     2-JUN-2015
ACCESSION   pNC011.xdna_(mod
VERSION     pNC011.xdna_(mod
KEYWORDS    .
FEATURES             Location/Qualifiers
     CDS             complement(7..633)
                     /label="tetR"
     misc_feature    complement(2921..3715)
                     /label="encodes nptII (aka AphA, neoR), gives kan and neo
                     resistance, with native promoter in on AatII and SpeI
                     from Lutz vector pZE2PLtetO-1 MCS2_Kan/neoR"
     promoter        634..706
                     /label="tet promoter region"
     RBS             722..741
                     /label="RBS"
     misc_feature    1840..1968
                     /label="dbl term"
     protein_bind    655..673
                     /label="Q1"
     protein_bind    685..701
                     /label="Q2"
     rep_origin      complement(2102..2784)
                     /label="colE1 origin"
     terminator      2790..2895
                     /label="T0"
     misc_feature    742..1815
                     /label="MCR"
ORIGIN      
        1 gacgtcttaa gacccacttt cacatttaag ttgtttttct aatccgcata tgatcaattc
       61 aaggccgaat aagaaggctg gctctgcacc ttggtgatca aataattcga tagcttgtcg
      121 taataatggc ggcatactat cagtagtagg tgtttccctt tcttctttag cgacttgatg
      181 ctcttgatct tccaatacgc aacctaaagt aaaatgcccc acagcgctga gtgcatataa
      241 tgcattctct agtgaaaaac cttgttggca taaaaaggct aattgatttt cgagagtttc
      301 atactgtttt tctgtaggcc gtgtacctaa atgtactttt gctccatcgc gatgacttag
      361 taaagcacat ctaaaacttt tagcgttatt acgtaaaaaa tcttgccagc tttccccttc
      421 taaagggcaa aagtgagtat ggtgcctatc taacatctca atggctaagg cgtcgagcaa
      481 agcccgctta ttttttacat gccaatacaa tgtaggctgc tctacaccta gcttctgggc
      541 gagtttacgg gttgttaaac cttcgattcc gacctcatta agcagctcta atgcgctgtt
      601 aatcacttta cttttatcta atctagacat cattaattcc taatttttgt tgacactcta
      661 tcgttgatag agttatttta ccactcccta tcagtgatag agaaaagaat tcaaaagatc
      721 ttttaagaag gagatataca tatgagaaga acgttaaaag cagccatcct cggcgcaacc
      781 ggtctggtgg gtattgagta tgttcgtatg ctgagcaatc acccgtacat taaacctgcg
      841 tatctggccg gtaagggtag cgttggtaag ccgtatggcg aggtcgtccg ttggcagacg
      901 gtcggccagg tgccgaaaga gatcgcggat atggagatta aaccgacgga cccgaagctg
      961 atggacgatg ttgatatcat cttctccccg ttgccgcagg gtgcggcagg tccggtcgag
     1021 gaacaatttg cgaaagaagg ttttccagtc atcagcaact cgccggacca ccgcttcgac
     1081 ccagacgtgc cgctgctggt gccggagctg aacccgcata ccatcagcct gatcgacgaa
     1141 cagcgtaaac gtcgcgaatg gaagggcttc atcgttacca ccccgctgtg cacggcgcaa
     1201 ggtgccgcga ttccgctggg tgcgattttc aaagattaca agatggatgg cgcgtttatc
     1261 actaccattc aatctctgtc cggtgcaggt tatcctggca ttccgagcct ggacgttgtt
     1321 gacaatatcc tgccgttggg cgatggttac gatgctaaga ccatcaaaga aatcttccgt
     1381 atcctgagcg aggtcaagcg taacgtggac gagccgaaac tggaagatgt ttctctggcg
     1441 gcgacgaccc atcgtattgc caccattcac ggtcattacg aggtgctgta tgttagcttt
     1501 aaagaagaaa cggcggctga gaaagtgaag gaaaccctgg agaacttccg tggtgagccg
     1561 caggacttga aactgccgac cgctccgagc aagccaatta tcgtgatgaa tgaggatacc
     1621 cgtccgcagg tatactttga ccgctgggca ggcgatattc cgggcatgag cgtggttgtc
     1681 ggccgtctga agcaagtgaa taagcgcatg attcgtctgg tcagcttgat tcacaacact
     1741 gttcgcggtg ctgcgggtgg cggcatcctg gcagccgagc tgctggtcga aaagggttac
     1801 attgaaaaat gataaggatc caaactcgag taaggatctc caggcatcaa ataaaacgaa
     1861 aggctcagtc gaaagactgg gcctttcgtt ttatctgttg tttgtcggtg aacgctctct
     1921 actagagtca cactggctca ccttcgggtg ggcctttctg cgtttatacc tagggcgttc
     1981 ggctgcggcg agcggtatca gctcactcaa aggcggtaat acggttatcc acagaatcag
     2041 gggataacgc aggaaagaac atgtgagcaa aaggccagca aaaggccagg aaccgtaaaa
     2101 aggccgcgtt gctggcgttt ttccataggc tccgcccccc tgacgagcat cacaaaaatc
     2161 gacgctcaag tcagaggtgg cgaaacccga caggactata aagataccag gcgtttcccc
     2221 ctggaagctc cctcgtgcgc tctcctgttc cgaccctgcc gcttaccgga tacctgtccg
     2281 cctttctccc ttcgggaagc gtggcgcttt ctcatagctc acgctgtagg tatctcagtt
     2341 cggtgtaggt cgttcgctcc aagctgggct gtgtgcacga accccccgtt cagcccgacc
     2401 gctgcgcctt atccggtaac tatcgtcttg agtccaaccc ggtaagacac gacttatcgc
     2461 cactggcagc agccactggt aacaggatta gcagagcgag gtatgtaggc ggtgctacag
     2521 agttcttgaa gtggtggcct aactacggct acactagaag gacagtattt ggtatctgcg
     2581 ctctgctgaa gccagttacc ttcggaaaaa gagttggtag ctcttgatcc ggcaaacaaa
     2641 ccaccgctgg tagcggtggt ttttttgttt gcaagcagca gattacgcgc agaaaaaaag
     2701 gatctcaaga agatcctttg atcttttcta cggggtctga cgctcagtgg aacgaaaact
     2761 cacgttaagg gattttggtc atgactagtg cttggattct caccaataaa aaacgcccgg
     2821 cggcaaccga gcgttctgaa caaatccaga tggagttctg aggtcattac tggatctatc
     2881 aacaggagtc caagcgagct ctcgaacccc agagtcccgc tcagaagaac tcgtcaagaa
     2941 ggcgatagaa ggcgatgcgc tgcgaatcgg gagcggcgat accgtaaagc acgaggaagc
     3001 ggtcagccca ttcgccgcca agctcttcag caatatcacg ggtagccaac gctatgtcct
     3061 gatagcggtc cgccacaccc agccggccac agtcgatgaa tccagaaaag cggccatttt
     3121 ccaccatgat attcggcaag caggcatcgc catgggtcac gacgagatcc tcgccgtcgg
     3181 gcatgcgcgc cttgagcctg gcgaacagtt cggctggcgc gagcccctga tgctcttcgt
     3241 ccagatcatc ctgatcgaca agaccggctt ccatccgagt acgtgctcgc tcgatgcgat
     3301 gtttcgcttg gtggtcgaat gggcaggtag ccggatcaag cgtatgcagc cgccgcattg
     3361 catcagccat gatggatact ttctcggcag gagcaaggtg agatgacagg agatcctgcc
     3421 ccggcacttc gcccaatagc agccagtccc ttcccgcttc agtgacaacg tcgagcacag
     3481 ctgcgcaagg aacgcccgtc gtggccagcc acgatagccg cgctgcctcg tcctgcagtt
     3541 cattcagggc accggacagg tcggtcttga caaaaagaac cgggcgcccc tgcgctgaca
     3601 gccggaacac ggcggcatca gagcagccga ttgtctgttg tgcccagtca tagccgaata
     3661 gcctctccac ccaagcggcc ggagaacctg cgtgcaatcc atcttgttca atcatgcgaa
     3721 acgatcctca tcctgtctct tgatcagatc atgatcccct gcgccatcag atccttggcg
     3781 gcaagaaagc catccagttt actttgcagg gcttcccaac cttaccagag ggcgccccag
     3841 ctggcaattc c    
//

**Comment by hplahar** [comment]
This has been fixed in the ICE application. Upload the file using the file upload in the entry view
