### ISSUE TITLE
Search algorithm can be improved?

### ISSUE THREAD

**Issue by sstonebloom** [JBEI/ice#26]
Dear Nathan / ICE development team,

The search algorithm that ICE uses is annoying to use and unpredictable. For example, for entries from Patrick Shih, if I search for "Patrick" the search returns Patrick Shih's entries, however if I search for "Shih" it returns entries from Adrienne Schlatter and David Shi but not Patrick Shih. 
The algorithm appears to require a match of complete words or the beginning of words to return entries.  An example of this behavior: I search for "tAtRbcS", looking for part ID "JBx_042288". This search returns nothing even though the keyword field for the entry is "{L_tAtRbcS}". 

Is there any way to improve the behavior of the search function?

many thanks,

Solomon

**Comment by hplahar** [comment]
Latest release has a bunch of search improvements
