### ISSUE TITLE
Can't find account passwords settings for ICE versions >4.1.18 deployed on AWS!

### ISSUE THREAD

**Issue by jmcarothers** [JBEI/ice#27]
For some reason, I'm not able to find anyplace to change the account passwords for ICE versions past 4.1.18.  Did a dropdown menu go missing?

**Comment by hplahar** [comment]
On the admin section of the site (your_domain/admin) make sure the setting "Password change allowed" is set to "yes". Users will now be able to change their passwords on their profile page (by clicking on the login id on the top right hand corner of the page when logged in)

**Comment by jmcarothers** [comment]
Thanks Hector, but for whatever reason, I’m not able to see anything, even with the password change set to “yes” — any other ideas?

Screenshots attached. —James

**Comment by hplahar** [comment]
Looks like the site is not recognizing various variants of "yes" e.g. Yes, YES

**Comment by hplahar** [comment]
Fixed in 4.3.5
