### ISSUE TITLE
Login and errors issues

### ISSUE THREAD

**Issue by cyrpaut** [JBEI/ice#31]
Hello Hector,

I've been working hard to deploy jbei ice for my lab in France. I've struggle to install it but I have a working protocol now. It is working fine and it is a great tool. I have the receipie to deploy it on ubuntu 10.04 server for ice 4.5.3.

However, troubles started the moment I deployed for the other users in my lab. The login system is not stable. When you create a new user and change its password, and then try to login with it, the login system breaks, and it is not possible to login anymore with either "Administrator"/"Administrator" or the newly created user. Worse than that, it seems to be an error at the java level, because malually deleting tomcat8 directories, the postgresql database and redeploying a new war does not make possible to login again.

I checked on maven:jetty and tomcat8 both my server and my virtual machine. The catalina.out / Stdout error is the following:

18:22:51.325 [1566159815@qtp-993774872-12] WARN  org.jbei.ice - Authentication failed for user Administrator
 
I checked in the code, and you seem to be the author of the AccountTransfer.java class which is giving back this error in AccessTokenResource.class. Could you help me fix that problem?

Thank you very much for your work on ice,

Cyrille

**Comment by hplahar** [comment]
Hi, Cyrille, 
Is there any error message in the logs? That warning message is not very informative since it always logs that when user authentication fails.

**Comment by cyrpaut** [comment]
Hi Hector,

No, there is not any other error I can find in catalina.out/other logs of tomcat, jetty stdout nor ice.log. Is there any other place where I can get this information?

I attached here all the logs from tomcat8 I get after (1 shutting down the server, 2 rm the logs, 3 starting up the server, 4 try to connect with Administrator/Administrator).

Is there what you want inside?

Thank you very much.

Cyrille

[catalina.2015-11-17.log.txt](https://github.com/JBEI/ice/files/36629/catalina.2015-11-17.log.txt)
[catalina.out.txt](https://github.com/JBEI/ice/files/36632/catalina.out.txt)

[localhost.2015-11-17.log.txt](https://github.com/JBEI/ice/files/36630/localhost.2015-11-17.log.txt)
[localhost_access_log.2015-11-17.txt](https://github.com/JBEI/ice/files/36631/localhost_access_log.2015-11-17.txt)

**Comment by hplahar** [comment]
Check to make sure that your hibernate connection parameters are in default.cfg.xml (or remove the defaults from there), if you are setting it in hibernate.cfg.xml.  From the logs, it is using the default embedded database (see below) but you mention using postgresql. 

Also, when you restart, does Administrator/Administrator login work?

`13:18:01.944 [localhost-startStop-1] INFO  org.hibernate.cfg.Configuration - HHH000043: Configuring from resource: hibernate.cfg.xml
13:18:01.945 [localhost-startStop-1] INFO  org.hibernate.cfg.Configuration - HHH000040: Configuration resource: hibernate.cfg.xml
13:18:02.033 [localhost-startStop-1] INFO  org.hibernate.cfg.Configuration - HHH000041: Configured SessionFactory: null
13:18:02.034 [localhost-startStop-1] INFO  org.hibernate.cfg.Configuration - HHH000043: Configuring from resource: default.cfg.xml
13:18:02.034 [localhost-startStop-1] INFO  org.hibernate.cfg.Configuration - HHH000040: Configuration resource: default.cfg.xml
13:18:02.038 [localhost-startStop-1] INFO  org.hibernate.cfg.Configuration - HHH000041: Configured SessionFactory: null
13:18:02.174 [localhost-startStop-1] INFO  o.h.c.i.C3P0ConnectionProvider - HHH010002: C3P0 using driver: org.h2.Driver at URL: jdbc:h2:./db/h2db
13:18:02.174 [localhost-startStop-1] INFO  o.h.c.i.C3P0ConnectionProvider - HHH000046: Connection properties: {user=sa, password=****}
13:18:02.175 [localhost-startStop-1] INFO  o.h.c.i.C3P0ConnectionProvider - HHH000006: Autocommit mode: false`

**Comment by cyrpaut** [comment]
Hi Hector,

Restarting the server does not allo Administrator/Administrator to be capable of logging in again. I haven't touched the files default.cfg.xml and hibernate.cfg.xml. There are the default files provided on github. Am I supposed to do anything with these files?

I have installed the postgresql but I haven't configured anything, assuming that the server would establish the connection by itself. I attached the procedure I followed to install ice my server from sources. Am I missing something here?

[INSTALL JBEI ICE.txt](https://github.com/JBEI/ice/files/38186/INSTALL.JBEI.ICE.txt)
[hibernate.cfg.xml.txt](https://github.com/JBEI/ice/files/38192/hibernate.cfg.xml.txt)
[default.cfg.xml.txt](https://github.com/JBEI/ice/files/38193/default.cfg.xml.txt)

Thank you very much,

Cyrille

**Comment by hplahar** [comment]
Hi, Cyrille,

ICE needs information about the database server before it can connect to it; including the password. This information should be set in default.cfg,xml. The default used when no changes are made is the embedded h2 database which resides at "./db/h2db". 

To change to postgres you can use the settings below changing the appropriate fields. (dbName, userName, password)
` <property name="hibernate.connection.url">jdbc:postgresql://localhost:5432/dbName</property>
    <property name="hibernate.connection.driver_class">org.postgresql.Driver</property>
    <property name="hibernate.connection.username">userName</property>
    <roperty name="hibernate.connection.password">Pa55WorD</property>
    <property name="hibernate.dialect">org.hibernate.dialect.PostgreSQL9Dialect</property>`

**Comment by cyrpaut** [comment]
Hi Hector,

Thank you for your answer, and sorry for not getting back to you earlier, I was very busy.

Indeed, I was missing the database connection part, which was documented nowhere, although it is logical, I couldn't have guessed the commands.

However, it does not solve the problem but I can reproduce it at will with the following commands.

sudo /bin/su - tomcat -c /usr/share/tomcat/bin/shutdown.sh
sudo rm -rf  /usr/share/tomcat/logs/*
sudo -u postgres psql --command "DROP DATABASE registry;"
sudo -u postgres psql --command "DROP USER tomcat;"
sudo -u postgres psql --command "CREATE DATABASE registry;"
sudo -u postgres psql --command "CREATE USER tomcat WITH PASSWORD '#########';"
sudo /bin/su - tomcat -c /usr/share/tomcat/bin/startup.sh

Then, once the server has rebooted I can login Administrator/Administrator... fine!
I go to the administration panel and i create a new user. I named it test test test@test.com.

![selection_040](https://cloud.githubusercontent.com/assets/15875320/11749492/5cf039aa-a02e-11e5-86d8-b72ce0e3242a.png)

There, I can logout as administrator and login as administrator again. fine!

Then I can go to the user and create the password. I made it "test", to be original.

![selection_041](https://cloud.githubusercontent.com/assets/15875320/11749551/be0e89d0-a02e-11e5-8a97-4de817d0990c.png)

I log out. Then I try to log as Administrator again. And then...

![selection_042](https://cloud.githubusercontent.com/assets/15875320/11749615/22d6777e-a02f-11e5-8b96-88b655677c0a.png)

Same for test@test.com / pw: "test"
![selection_043](https://cloud.githubusercontent.com/assets/15875320/11749639/40401dce-a02f-11e5-8a07-aed436719933.png)

Here is the catalina.out
[catalina.out.txt](https://github.com/JBEI/ice/files/59630/catalina.out.txt)

If you re-run the commands I gave you in the beginning of the mail. You can fix and then get the bug again. (I did it twice to be sure).

What can we do to fix that? Is it a problem you have on your side? It happens on fresh compilation, on fresh linux following the instructions I gave you before.

Thank you very much

**Comment by hplahar** [comment]
Thanks for the detailed steps. It helped me understand what is going on. There is indeed a bug. When you (as an administrator) change the password on the user's page, the bug is causing the administrator's password to be changed instead. Try logging in using the "test" password and "Administrator" as the email to verify. I will have a fix later today or on monday.

Sorry for the lack of documentation. I am working on detailed installation and user guides. But that is still several weeks away.

**Comment by cyrpaut** [comment]
Hi Hector,

Thanks for helping me with this bug. Indeed, Administrator/ pw: test works. I didn't thought it could be that simple. I thought that it might be the authentication chain that gets broken.

Let me know when the bug is fixed so that I could deploy the server. 

BTW for the documentation, feel free to reuse mine, it took me several hours of work to make it and I used several time to deploy my server and virtual machine so I know it works well on the latest LTS Ubuntu. Might get a bit different when Tomcat8 and Java8 will be in the official repos of ubuntu. I don't know if it is going to be in the next LTS version. The only thing is to add the connector part that you suggested me and then it is going to be fine!

**Comment by hplahar** [comment]
Fixed pushed to version 4.5.4

**Comment by cyrpaut** [comment]
Hi Hector,

I did wipe my server, wipe my git, pull everything again, compile and deploy again. I could not even connect through Administrator/Administrator. Please note that I have not reset the connector to postgresql and it it the plain default h2db.

Here is the catalina.out [catalina.out.txt](https://github.com/JBEI/ice/files/62306/catalina.out.txt)

However, I don't have the problem on maven.

Any idea where this come from?

**Comment by hplahar** [comment]
You will also have to delete the db files (./db/h2db).

**Comment by cyrpaut** [comment]
Oups indeed. I didn't thought this file could be in the /home folder.

For the record, here is the updated installation procedure. You could use it if you wish. 
[INSTALL JBEI ICE.txt](https://github.com/JBEI/ice/files/63073/INSTALL.JBEI.ICE.txt)

Thanks a lot for your help!
