### ISSUE TITLE
No sign up possible

### ISSUE THREAD

**Issue by AuroreFMN** [JBEI/ice#34]
On the home page, the "here" link that should allow you to create a new account leads to a 404 error message.

**Comment by hplahar** [comment]
Can you provide more information? Which "here" link are you referring to?

On the login in page (https://public-registry.jbei.org/login) the link to create an account is a button ("Create Account") which takes you to https://public-registry.jbei.org/register to create an account

**Comment by AuroreFMN** [comment]
Sorry, I'm talking about the SynBERC home page 
https://registry.synberc.org/#page=login
I'll create an account from jbei home page, but FYI, the link to create an account on SynBERC ("Don't have a SynBERC login? Go here to create an account first.") is not working

**Comment by hplahar** [comment]
I have brought this to Kevin's attention and they are working on it. Closing this since it is not a functionality in ICE
