### ISSUE TITLE
Batch Import GenBank Files and Sample Location Information

### ISSUE THREAD

**Issue by bdanford** [JBEI/ice#36]
Hi,

I’m looking at ICE (5.0.x) and would like to know how I would _batch_ import multiple GenBank files and sample location information for a large number of parts. Right now, it seems I would have to click and choose a GenBank file for each row of a batch upload.
1. If I skip filling in the rows in the batch upload, is there any way to do this using the API? Do you have any suggestions for how to get started? An example API call would help.
2. I would also like to do a similar call to add new or updated sample location for each part. Is that possible?

Thanks

**Comment by hplahar** [comment]
Hello

1. Did you try using the bulk file upload? You can see how to do it here: http://ice.jbei.org/manual/bulk_file_upload.html. Let me know if that is not what you need.

2. To add a sample using the API requires sending a `POST` to `/rest/parts/{id}/samples` (where `{id}` is the part identifier) with the [PartSample.](https://github.com/JBEI/ice/blob/master/src/main/java/org/jbei/ice/lib/dto/sample/PartSample.java) object. Accepts JSON. The relevant fields of the object are the label, depositer and location. I can put together an example of that will be helpful

**Comment by hplahar** [comment]
Actually, I just remembered that there is a way to create samples using the same bulk file upload by adding columns to the spreadsheet. This feature is hidden because I implemented it for a specific use case for another user. Let me know what your sample storage location format looks like and I can check if it will work for you

**Comment by bdanford** [comment]
Thank you for your quick response!

1. I see now how to bulk upload GenBank files. The video was very helpful.

2. With respect to adding samples, either a 96-well plate (or 24-well plate) or a shelf/box/tube system would be useful. If you have a straightforward way to add this to the bulk import, that would be fantastic. If not, then perhaps you can send an example of how to add a sample using the API.

3. Is it possible to add an arbitrary field (i.e., column) to the CSV template? For example, if I want to have an "amino acid ID" field, can I add this as a column for bulk import? My initial attempt appears as if this can't be done.

4. I noticed in the manual that there is a way to do a "bulk update." Can you explain how to do this?

I appreciate your help with this.

**Comment by hplahar** [comment]
2. You can add shelf/box/well using bulk upload. When you download the template for your upload you need to manually add 4 columns with the headers "Shelf", "Box", "Well", "Label". (Label is to enable adding a short description.) Let me know if this does not work. I am updating the documentation for the REST API to include samples creation.

3. Currently, it is not possible to do so. This is a planned feature. You can do it when creating single entries but not with bulk update.

4. You can only bulk edit entries of the same type (e.g. plasmids only or strains only). To do so, select any number of entries of the same type in the table view and click edit. You will be shown the bulk upload interface and you can make changes. Click the "done" button when finished.

Thanks.

**Comment by csawye01** [comment]
Hello,

Was the example file for adding a sample using the API end up being written and if so where could I find it? 
Thanks!
