### ISSUE TITLE
Can't retrieve sequence information from REST API?

### ISSUE THREAD

**Issue by udp** [JBEI/ice#40]
The RESTful API documented at http://ice.jbei.org/api/index.html does not seem to have any functions to retrieve sequence information for a part.  I can retrieve a JSON object with metadata, but the sequence is not present.

**Comment by hplahar** [comment]
There are two ways to do it and it appears I neglected to document both:

1. ```GET rest/:id/sequence``` with return a JSON object representation of the sequence and annotations. ``:id`` is the identifier for the part whose sequence is being retrieved (e.g. 4312)

2. ``GET rest/file/:id/sequence/:type`` will allow you to download the binary sequence file (octet stream). ``:id`` is the partId and ``:type`` is one of ``original``  ``genbank``  ``fasta`` ``sbol1``  ``sbol2``. ``original`` is used to download the file as was uploaded.

I will add those to the documentation soon

**Comment by udp** [comment]
Great, thanks! :-)
