### ISSUE TITLE
Multiline notes in Genbank files cause problems

### ISSUE THREAD

**Issue by alaninmcr** [JBEI/ice#44]
Although the data is parsed, it also truncates the lines to one and the extra lines bleed into other parts of the construct's sequence information.

Erroneous things are seen at the beginning of the pigeon image

![pigeon](https://cloud.githubusercontent.com/assets/349232/20181299/79370c22-a755-11e6-89e7-4868adaa8475.PNG)

The VectorEditor also shows strange information at the beginning of the sequence

![vectorelement](https://cloud.githubusercontent.com/assets/349232/20181329/a8b2ceb4-a755-11e6-91d5-6f1b79af0a11.PNG)

I have a drafty patch for GenBankParser

**Comment by hplahar** [comment]
Thanks. Once the patch is finalized can you submit a pull request?

**Comment by lyschoening** [comment]
What's the status on this?

**Comment by alaninmcr** [comment]
On 08/03/2017 13:39, Lars Schöning wrote:
> What's the status on this?

I have just created a pull request.

Alan
