### ISSUE TITLE
When creating a sequence from a file two entries are created

### ISSUE THREAD

**Issue by cjmyers** [JBEI/ice#54]
When a part is created using the upload of an SBOL file, two entries are created.  Only one of them shows up though in the list of entries, and the id returned by the endpoint is for the entry that does not show up.  Should only create one entry and send that id back.

**Comment by aitorbk** [comment]
Hi!
What version of ICE have you tested this on?

**Comment by cjmyers** [comment]
Latest from github.  We met with Hector yesterday and work out a plan to sort this one.  Namely, we need a switch to either generate the part from SBOL converted to GenBank (i.e., a flat record) OR create a hierarchy of parts from the SBOL file itself.  This will be an additional rest form parameter with the default if not present of generating a single flat record.

**Comment by hplahar** [comment]
`extractHierarchy` parameter added. If set to `true`, hierarchy of parts from the SBOL file is created
