### ISSUE TITLE
Plasmids do not seem to be publicly visible

### ISSUE THREAD

**Issue by ErikHanko** [JBEI/ice#59]
I submitted 5 plasmids as part of a publication to the JBEI public registry. Plasmids pEH006, pEH007, pEH008, pEH009 and pEH010 have been assigned IDs JPUB_008750-JPUB_008754, respectively. I have been contacted by several people that only pEH006 can be accessed. Is it a bug or why are all the plasmids shown to be publicly available on my account but for nobody else? Apparently, they can not be found using either their name or accession number.
Please let me know whether I have to click another box to make them available.

Kind regards,
Erik Hanko

**Comment by hplahar** [comment]
It works for me as well. Can you have them try accessing it using the direct links? e.g. https://public-registry.jbei.org/entry/8751
