### ISSUE TITLE
vector editor save fails with j5.jbei.org/j5bin/crossdomain.xml 403 (Forbidden)

### ISSUE THREAD

**Issue by cfblaeb** [JBEI/ice#61]
Cant save in vector editor.
I tested latest release as well as the dev branch and in both of them I cant save changes to plasmids from the vector editor (but I can from the auto-annotator).
I tested latest versions of Chrome, Firefox and Internet Explorer on Windows 7 and Ubuntu 17.04.
All with their respective latest flash plugin.

Specifically I click the save icon in the vector editor and I get a message ( I think from the flash plugin ) "ioErrorHandler: Error #2032".
Chrome and firefox additionally give me a POST error in console:
POST https://dhcp-10-75-3-178:8443/rest/parts/42106587-df02-4e57-b130-32d78e4d0b51/sequence?sid=93d578b9-0407-48aa-a882-2b3b5b4ed16a 404 (Not Found)    sequence:1 

A manual GET to that URL returns a JSON version of the plasmid.

Additionally Chrome get a 403 after trying to save:
GET https://j5.jbei.org/j5bin/crossdomain.xml 403 (Forbidden)

And Firefox gets a 404 when entering the editor, though everything seems to work in the editor.
GET https://dhcp-10-75-3-178:8443/static/swf/ve/VectorEditor

**Comment by cfblaeb** [comment]
Just tested on public-registry.jbei.org and I get the same error there.

**Comment by hplahar** [comment]
Thanks for the details. Should be fixed.
