### ISSUE TITLE
ICE shared folders - missing 'next' button

### ISSUE THREAD

**Issue by aruffinABF** [JBEI/ice#62]
When I open a shared folder on ICE, it lists the first 30 parts but there is no button or link to advance to the next set of parts. (see screenshot below ... it says '1-30 of 157' at the bottom but there is no way to advance)

![image](https://user-images.githubusercontent.com/33553796/32670063-d577c0d4-c5ff-11e7-9814-ed2d1ea159bb.png)

**Comment by hplahar** [comment]
Fixed
