### ISSUE TITLE
Bulk upload is not working in ICE

### ISSUE THREAD

**Issue by aruffinABF** [JBEI/ice#66]
I receive the error below when submitting a bulk upload. All of the required fields have been filled out, so it is unclear what will fix the issue.

![image](https://user-images.githubusercontent.com/33553796/33498841-2221d88e-d690-11e7-9c02-fcddfca919d9.png)

**Comment by aitorbk** [comment]
Hi aruffinABF, if you provide me a file example (remove all propietary data) I can figure out your problems if you still gave them.

**Comment by aruffinABF** [comment]
I just tried using the .csv template, and I get the error below. I'm currently checking to make sure it does not contain proprietary data, then I will send you the file.
<img width="932" alt="180223_bulk_upload_error_ice" src="https://user-images.githubusercontent.com/33553796/36613703-86bd4ea6-1897-11e8-8782-1308cb19d612.png">

**Comment by hplahar** [comment]
Send it to me separately via email
