### ISSUE TITLE
Can't log in or create account

### ISSUE THREAD

**Issue by Fontanapink** [JBEI/ice#75]
Hello, 
         I have an ACS account and I am trying to log in to the ICE registry but cannot do so with my ACS account. Also tried creating a new account and it only says: "Error creating account". Is this because I am trying to use my gmail account instead of an Institution account?

**Comment by hplahar** [comment]
The error was because you were trying to create a new account using the same gmail as the existing account. I just triggered a password reset for your account and you should receive an email containing a temp password that you can use to login.
