### ISSUE TITLE
Docker solution ?

### ISSUE THREAD

**Issue by Zulko** [JBEI/ice#76]
Hi there,

Has anyone had any success with a docker configuration ICE ? A dockerized ICE would be much easier to deploy and try out. Are there some hurdles to dockerizing ICE in particular ?

Thanks !

**Comment by Mulgie11** [comment]
Hi Zulko, 

I'm unsure of what you mean as there has been an ICE Docker available for quite some time; see here:
https://github.com/JBEI/ice/tree/master/docker

Kindest regards.

**Comment by Zulko** [comment]
I am an idiot, I was looking for a Docker file at the root and missed the folder. Thanks @Mulgie11 and Sorry for the noise.

**Comment by Mulgie11** [comment]
Hi Zulko,

No worries fella, you're most welcome.  To be homest I didn't see it the first time I visited this site either as there is no mention of Docker in the README.md file! :)
