### ISSUE TITLE
Repo broken, error in comments 

### ISSUE THREAD

**Issue by jurquiza** [JBEI/ice#84]
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 40.589 s
[INFO] Finished at: 2018-12-05T12:01:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ice: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
ERROR: Service 'ice' failed to build: The command '/bin/sh -c sed -i.bak -E         -e 's/<security-constraint>//;'         /ice/src/main/webapp/WEB-INF/web.xml     && rm /ice/src/main/webapp/WEB-INF/web.xml.bak     && mvn -Dwar.warName=ice package' returned a non-zero code: 1

**Comment by hplahar** [comment]
Neither [Travis](https://travis-ci.org/JBEI/ice) nor [TeamCity](http://registry-test.jbei.org:8111/viewType.html?buildTypeId=ice_Master) is reporting any issues with the build. Likely to be a local issue
