### ISSUE TITLE
error when installing using docker

### ISSUE THREAD

**Issue by jurquiza** [JBEI/ice#95]
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar (37 kB at 1.4 MB/s)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 44.315 s
[INFO] Finished at: 2019-11-18T11:21:52Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ice: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
ERROR: Service 'ice' failed to build: The command '/bin/sh -c sed -i.bak -E         -e 's/<security-constraint>//;'         /ice/src/main/webapp/WEB-INF/web.xml     && rm /ice/src/main/webapp/WEB-INF/web.xml.bak     && mvn -Dwar.warName=ice package' returned a non-zero code: 1

**Comment by Lix1993** [comment]
same error：

```
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/surefire/surefire-junit4/2.12.4/surefire-junit4-2.12.4.jar (37 kB at 80 kB/s)

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Error: Could not find or load main class org.apache.maven.surefire.booter.ForkedBooter

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:07 min
[INFO] Finished at: 2019-11-19T02:37:03Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ice: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
The command '/bin/sh -c sed -i.bak -E         -e 's/<security-constraint>/<!--<security-constraint>/;'         -e 's/<\/security-constraint>/<\/security-constraint>-->/;'         /ice/src/main/webapp/WEB-INF/web.xml     && rm /ice/src/main/webapp/WEB-INF/web.xml.bak     && mvn -Dwar.warName=ice package' returned a non-zero code: 1
```

**Comment by veghp** [comment]
Same error here. Any updates on this?

**Comment by jurquiza** [comment]
This as not been resolved

**Comment by hplahar** [comment]
@wmorrell can you look into this?

**Comment by wmorrell** [comment]
It's been a while since I put the Dockerfile together, and some things in Maven got deprecated since then. I'll put together a pull request from the changes in the Docker bootcamp in February, which … worked in February. Hopefully it's working still.

**Comment by jurquiza** [comment]
if i try to compile the container it gave the error

E: Version '2.6.0-1' for 'ncbi-blast+' was not found

Then if i run the docker-compose up it gives and error regarding the postgres database 

because it is now pulling the image from dockerhub I suppose. 

Creating docker_postgres_1 ... done
Creating docker_ice_1      ... done
Attaching to docker_ice_1, docker_postgres_1
postgres_1  | Error: Database is uninitialized and superuser password is not specified.
postgres_1  |        You must specify POSTGRES_PASSWORD to a non-empty value for the
postgres_1  |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
postgres_1  | 
postgres_1  |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
postgres_1  |        connections without a password. This is *not* recommended.
postgres_1  | 
postgres_1  |        See PostgreSQL documentation about "trust":
postgres_1  |        https://www.postgresql.org/docs/current/auth-trust.html
docker_postgres_1 exited with code 1

**Comment by jurquiza** [comment]
So i fixed the issues and now up and running. 

First I modified the Dockerfile, removing the pinned down version. This has to be addressed.

Second I changed the docker-compose.yml file such that the environmental variables are now set from an external file 

  postgres:
    image: library/postgres:latest
    env_file:
      - database.env

#databse.env has 
POSTGRES_USER=iceuser
POSTGRES_PASSWORD=icepass
POSTGRES_DB=ice

so the first compile the Docker container and the do docker-compose up 
access then on localhost:9999

**Comment by wmorrell** [comment]
The version needs to be pinned for repeatable builds. Looks like the original 2.6.0-1 version from Debian upstream is no longer available as of recently. It should be updated to the current latest in buster, 2.8.1-1, else install from source at a pinned version.

**Comment by luizimgiolo** [comment]
With the last update the build has been succefull

'''
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.796 s
[INFO] Finished at: 2022-04-27T12:25:51Z
[INFO] ------------------------------------------------------------------------

'''

But I'm having "HTTP Status 404 – Not Found" at localhost:9999.
The container is working, once the error is coming from tomcat, but postgres does not apear at my docker ps status

CONTAINER ID   IMAGE             COMMAND             CREATED          STATUS          PORTS                      NAMES
db3b4cea2286   jbei/ice:latest   "catalina.sh run"   11 minutes ago   Up 11 minutes   127.0.0.1:9999->8080/tcp   docker_ice_1

**Comment by wmorrell** [comment]
The original issue is resolved.

@luizimgiolo as described in the README, the default Docker build comes with a `docker-compose.yml` for development and launches a Postgres database container. Running the container by itself—as shown in your `docker ps` output—requires passing a set of database connection parameters with the `CATALINA_OPTS` environment. e.g. `docker run --rm --env "CATALINA_OPTS=-Dice.db.url=postgresql://db.example.net:5432/ice -Dice.db.user=ice -Dice.db.pass=correct.horse.battery.staple" jbei/ice:latest`.
